In [45]:
import numpy as np
import pandas as pd
from scipy import optimize
xx=[]
yy=[]
x_N=[]
for a in ['1.dat', '2.dat', '3.dat', '4.dat', '5.dat', '6.dat', '7.dat', '8.dat', '9.dat', '10.dat', '11.dat', '12.dat', '13.dat', '14.dat',]: 
    data1=pd.read_table(a, sep='\s+', names=['a', 'b','c']) 
    x_data=data1['a']
    xx = np.hstack([
        xx,
        x_data
    ]).T
    
    yy = np.hstack([
        yy,
        data1['b']
    ]).T
    x_data=data1['a']
    x_N.append(len(x_data))
Tc=np.array([1.029307615,0.670808905,0.195557495,0.402425385,0.917117575,0.540860525,0.590357705,1.115106295,0.689352065,0.92678156,0.976278745,1.025775925,1.015719525,0.540468115])
def idx(i,j):
    return sum(x_N[:i]) + j
for i in range(14):
    xx[idx(i, 0):idx(i+1, 0)]=xx[idx(i, 0):idx(i+1, 0)]-Tc[i]
    #print(xx[idx(i, 0):idx(i+1, 0)])
def f(xx, *param):
    return np.hstack([
        param[4*i]*xx[idx(i, 0):idx(i+1, 0)]**3 + param[4*i+1]*xx[idx(i, 0):idx(i+1, 0)]**2+param[4*i+2]*xx[idx(i, 0):idx(i+1, 0)]+param[4*i+3] for i in range(14)
    ])
def Psi(D,x,y):
    if D==0:
        if x**2-y**2 < 0:
            return np.pi
        else:
            return 0.0
    else:
        return np.real(np.arccos((x**2+D**2-y**2)/(2*D*x)+0j))

def Q(d,r):
    return np.real(np.sqrt((1-(d-r)**2)*((d+r)**2-1)+0j))

def eclips(d,r):
    return np.array([Psi(d_cur,1,r)+Psi(d_cur,r,1)*r**2-Q(d_cur,r)/2 for d_cur in d])

def delta_x(t,t0,tau,l):
    return np.abs(t-t0)/tau*l

def delta(delta_x,impact):
    return np.sqrt(delta_x**2+impact**2)

def fun(t,tau,l,r,impact,L_st,C,t0):
    return L_st+C*(np.pi-eclips(delta(delta_x(t,t0,tau,l),impact),r))

R_st= 1.155 #в радиусаз Солнца +0.014−0.016
R_pl= 1.359 #в радиусах Юпитера +0.016−0.019
au  = 0.04707 #большая полуось в а.е. +0.00045−0.00047
i   = 86.710 #наклон орбиты ±0.050
P   = 3.52474859  #период в днях ±3.8e-07 
MidT= 2826.629283 #среднее время транзита ±8.7e-05
tn  = 218.17120131500087#Время центра затмения
r=R_st/R_pl*695700/71492
impact=au*np.cos(i/180*np.pi)/R_pl/71492*149597870
l=np.sqrt((r+1)**2-impact**2)
tau = P*np.arcsin(l*R_pl*71492/au/149597870)/2/np.pi#длительность транзита
    
def fun2(xx, a1,b1,c1,d1,a2,b2,c2,d2,a3,b3,c3,d3,a4,b4,c4,d4,a5,b5,c5,d5,a6,b6,c6,d6,a7,b7,c7,d7,a8,b8,c8,d8,a9,b9,c9,d9,a10,b10,c10,d10,a11,b11,c11,d11,a12,b12,c12,d12,a13,b13,c13,d13,a14,b14,c14,d14,C,t0):
    return f(xx, a1,b1,c1,d1,a2,b2,c2,d2,a3,b3,c3,d3,a4,b4,c4,d4,a5,b5,c5,d5,a6,b6,c6,d6,a7,b7,c7,d7,a8,b8,c8,d8,a9,b9,c9,d9,a10,b10,c10,d10,a11,b11,c11,d11,a12,b12,c12,d12,a13,b13,c13,d13,a14,b14,c14,d14)+C/np.pi*(np.pi-eclips(delta(delta_x(xx,t0,tau,l),impact),r))

zz1=np.zeros((np.size(xx)))
zz1[idx(0, 0):idx(1, 0)]=1
zz2=np.zeros((np.size(xx)))
zz2[idx(1, 0):idx(2, 0)]=1
zz3=np.zeros((np.size(xx)))
zz3[idx(2, 0):idx(3, 0)]=1
zz4=np.zeros((np.size(xx)))
zz4[idx(3, 0):idx(4, 0)]=1
zz5=np.zeros((np.size(xx)))
zz5[idx(4, 0):idx(5, 0)]=1
zz6=np.zeros((np.size(xx)))
zz6[idx(5, 0):idx(6, 0)]=1
zz7=np.zeros((np.size(xx)))
zz7[idx(6, 0):idx(7, 0)]=1
zz8=np.zeros((np.size(xx)))
zz8[idx(7, 0):idx(8, 0)]=1
zz9=np.zeros((np.size(xx)))
zz9[idx(8, 0):idx(9, 0)]=1
zz10=np.zeros((np.size(xx)))
zz10[idx(9, 0):idx(10, 0)]=1
zz11=np.zeros((np.size(xx)))
zz11[idx(10, 0):idx(11, 0)]=1
zz12=np.zeros((np.size(xx)))
zz12[idx(11, 0):idx(12, 0)]=1
zz13=np.zeros((np.size(xx)))
zz13[idx(12, 0):idx(13, 0)]=1
zz14=np.zeros((np.size(xx)))
zz14[idx(13, 0):idx(14, 0)]=1



params, params_covariance = optimize.curve_fit(fun2, xx, yy,p0=[0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0])


In [46]:
params

array([-9.06800931e-01,  1.26972338e-01,  2.88264873e-02,  9.97626784e-01,
       -3.54258946e-02,  4.61223633e-02, -2.91258980e-02,  9.99004877e-01,
        1.30442893e-01, -5.09599312e-02, -4.28030765e-02,  1.00019513e+00,
        2.04572410e-01, -8.28656841e-02,  6.98858327e-02,  1.00372588e+00,
       -5.72242299e-01, -2.58774468e-01,  5.62117682e-02,  1.00000108e+00,
       -2.15690768e+00, -7.27722636e-02,  8.45059243e-02,  1.00290832e+00,
        4.93909479e-01, -2.22921441e-01,  2.90256485e-02,  9.99315974e-01,
       -4.64129616e-01,  3.25815803e-02, -8.68639110e-04,  9.98497502e-01,
        1.64133490e+00,  1.47808610e-02,  1.85802740e-02,  9.99981679e-01,
        3.28394040e+00, -4.37437571e-01,  1.91060666e-02,  1.00409470e+00,
        3.81328031e-01, -1.58383473e-01,  4.02655889e-02,  1.00025987e+00,
       -2.84061687e+00, -1.88848364e-01,  5.00840135e-02,  1.00188907e+00,
        7.82084037e-01, -8.28762300e-02, -5.54440335e-03,  1.00067053e+00,
        3.43612264e+00,  

In [49]:
 
perr =np.sqrt(np.diag(params_covariance))
np.sqrt(np.diag(params_covariance))

array([1.80169750e-01, 1.68369806e-02, 3.33781923e-03, 2.01743336e-04,
       7.14389131e-02, 6.48327721e-03, 1.35474417e-03, 8.12144477e-05,
       7.14313398e-02, 6.52197575e-03, 1.35306929e-03, 8.12815958e-05,
       6.46860169e-02, 6.66369953e-03, 1.27374627e-03, 8.12248053e-05,
       1.66897800e-01, 1.19162078e-02, 1.95505800e-03, 8.99129266e-05,
       1.67684977e-01, 1.32286421e-02, 1.92120186e-03, 9.12228258e-05,
       1.13384290e-01, 1.09914545e-02, 1.58337537e-03, 8.81519005e-05,
       9.68678141e-02, 8.69141879e-03, 1.52410652e-03, 8.48140118e-05,
       1.68284964e-01, 1.45021546e-02, 1.88380276e-03, 9.25766751e-05,
       1.67513284e-01, 1.30578338e-02, 1.92548114e-03, 9.10511294e-05,
       1.68307681e-01, 1.47408264e-02, 1.87597411e-03, 9.28414688e-05,
       2.01869109e-01, 1.37079945e-02, 2.12130580e-03, 9.22361091e-05,
       2.51267104e-01, 1.60932649e-02, 2.32997004e-03, 9.50563084e-05,
       1.67391930e-01, 1.26620591e-02, 1.93669784e-03, 9.06400515e-05,
      

In [113]:
import numpy as np
import pandas as pd
from scipy import optimize
xx=[]
yy=[]
x_N=[]
for a in ['1.dat', '2.dat', '3.dat', '4.dat', '5.dat', '6.dat', '7.dat', '8.dat', '9.dat', '10.dat', '11.dat', '12.dat', '13.dat', '14.dat',]: 
    data1=pd.read_table(a, sep='\s+', names=['a', 'b','c']) #Заменить aaa на имя файла
    x_data=data1['a']
    #print(x_data)
    xx = np.hstack([
        xx,
        x_data
    ]).T
    
    yy = np.hstack([
        yy,
        data1['b']
    ]).T
    x_data=data1['a']
    x_N.append(len(x_data))
Tc=np.array([1.029307615,0.670808905,0.195557495,0.402425385,0.917117575,0.540860525,0.590357705,1.115106295,0.689352065,0.92678156,0.976278745,1.025775925,1.015719525,0.540468115])
def idx(i,j):
    return sum(x_N[:i]) + j
for i in range(14):
    xx[idx(i, 0):idx(i+1, 0)]=xx[idx(i, 0):idx(i+1, 0)]-Tc[i]
    #print(xx[idx(i, 0):idx(i+1, 0)])
def f(xx, *param):
    return np.hstack([
        param[4*i]*xx[idx(i, 0):idx(i+1, 0)]**3 + param[4*i+1]*xx[idx(i, 0):idx(i+1, 0)]**2+param[4*i+2]*xx[idx(i, 0):idx(i+1, 0)]+param[4*i+3] for i in range(14)
    ])
def Psi(D,x,y):
    if D==0:
        if x**2-y**2 < 0:
            return np.pi
        else:
            return 0.0
    else:
        return np.real(np.arccos((x**2+D**2-y**2)/(2*D*x)+0j))

def Q(d,r):
    return np.real(np.sqrt((1-(d-r)**2)*((d+r)**2-1)+0j))

def eclips(d,r):
    return np.array([Psi(d_cur,1,r)+Psi(d_cur,r,1)*r**2-Q(d_cur,r)/2 for d_cur in d])

def delta_x(t,t0,tau,l):
    return np.abs(t-t0)/tau*l

def delta(delta_x,impact):
    return np.sqrt(delta_x**2+impact**2)

def fun(t,tau,l,r,impact,L_st,C,t0):
    return L_st+C*(np.pi-eclips(delta(delta_x(t,t0,tau,l),impact),r))

R_st= 1.155 #в радиусаз Солнца +0.014−0.016
R_pl= 1.359 #в радиусах Юпитера +0.016−0.019
au  = 0.04707 #большая полуось в а.е. +0.00045−0.00047
i   = 86.710 #наклон орбиты ±0.050
P   = 3.52474859  #период в днях ±3.8e-07 
MidT= 2826.629283 #среднее время транзита ±8.7e-05
tn  = 218.17120131500087#Время центра затмения
r=R_st/R_pl*695700/71492
impact=au*np.cos(i/180*np.pi)/R_pl/71492*149597870
l=np.sqrt((r+1)**2-impact**2)
tau = P*np.arcsin(l*R_pl*71492/au/149597870)/2/np.pi#длительность транзита
    
def fun2(xx, a1,b1,c1,d1,a2,b2,c2,d2,a3,b3,c3,d3,a4,b4,c4,d4,a5,b5,c5,d5,a6,b6,c6,d6,a7,b7,c7,d7,a8,b8,c8,d8,a9,b9,c9,d9,a10,b10,c10,d10,a11,b11,c11,d11,a12,b12,c12,d12,a13,b13,c13,d13,a14,b14,c14,d14,C,t0):
    return f(xx, a1,b1,c1,d1,a2,b2,c2,d2,a3,b3,c3,d3,a4,b4,c4,d4,a5,b5,c5,d5,a6,b6,c6,d6,a7,b7,c7,d7,a8,b8,c8,d8,a9,b9,c9,d9,a10,b10,c10,d10,a11,b11,c11,d11,a12,b12,c12,d12,a13,b13,c13,d13,a14,b14,c14,d14)+C/np.pi*(np.pi-eclips(delta(delta_x(xx,t0,tau,l),impact),r))

zz1=np.zeros((np.size(xx)))
zz1[idx(0, 0):idx(1, 0)]=1
zz2=np.zeros((np.size(xx)))
zz2[idx(1, 0):idx(2, 0)]=1
zz3=np.zeros((np.size(xx)))
zz3[idx(2, 0):idx(3, 0)]=1
zz4=np.zeros((np.size(xx)))
zz4[idx(3, 0):idx(4, 0)]=1
zz5=np.zeros((np.size(xx)))
zz5[idx(4, 0):idx(5, 0)]=1
zz6=np.zeros((np.size(xx)))
zz6[idx(5, 0):idx(6, 0)]=1
zz7=np.zeros((np.size(xx)))
zz7[idx(6, 0):idx(7, 0)]=1
zz8=np.zeros((np.size(xx)))
zz8[idx(7, 0):idx(8, 0)]=1
zz9=np.zeros((np.size(xx)))
zz9[idx(8, 0):idx(9, 0)]=1
zz10=np.zeros((np.size(xx)))
zz10[idx(9, 0):idx(10, 0)]=1
zz11=np.zeros((np.size(xx)))
zz11[idx(10, 0):idx(11, 0)]=1
zz12=np.zeros((np.size(xx)))
zz12[idx(11, 0):idx(12, 0)]=1
zz13=np.zeros((np.size(xx)))
zz13[idx(12, 0):idx(13, 0)]=1
zz14=np.zeros((np.size(xx)))
zz14[idx(13, 0):idx(14, 0)]=1

def jacobian(x, a1,b1,c1,d1,a2,b2,c2,d2,a3,b3,c3,d3,a4,b4,c4,d4,a5,b5,c5,d5,a6,b6,c6,d6,a7,b7,c7,d7,a8,b8,c8,d8,a9,b9,c9,d9,a10,b10,c10,d10,a11,b11,c11,d11,a12,b12,c12,d12,a13,b13,c13,d13,a14,b14,c14,d14,C,t0):
    dC   =1.0-eclips(delta(delta_x(x,t0,tau,l),impact),r)/np.pi
    dt0  =C*Q(delta(delta_x(x,t0,tau,l),impact),r)*(x-t0)*(l/(tau*delta(delta_x(x,t0,tau,l),impact)))**2
    print(dC)
    return np.transpose([zz1*x**3,zz1*x**2,zz1*x,zz1,zz2*x**3,zz2*x**2,zz2*x,zz2,zz3*x**3,zz3*x**2,zz3*x,zz3,zz4*x**3,zz4*x**2,zz4*x,zz4,zz5*x**3,zz5*x**2,zz5*x,zz5,zz6*x**3,zz6*x**2,zz6*x,zz6,\
                         zz7*x**3,zz7*x**2,zz7*x,zz7,zz8*x**3,zz8*x**2,zz8*x,zz8,zz9*x**3,zz9*x**2,zz9*x,zz9,zz10*x**3,zz10*x**2,zz10*x,zz10,zz11*x**3,zz11*x**2,zz11*x,zz11,zz12*x**3,zz12*x**2,zz12*x,zz12,\
                         zz13*x**3,zz13*x**2,zz13*x,zz13,zz14*x**3,zz14*x**2,zz14*x,zz14,dC,dt0])

params, params_covariance = optimize.curve_fit(fun2, xx, yy,jac=jacobian,p0=[0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0])


[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]


In [110]:
params

array([-9.06801329e-01,  1.26972224e-01,  2.88264934e-02,  9.97626783e-01,
       -3.54240477e-02,  4.61222851e-02, -2.91259293e-02,  9.99004875e-01,
        1.30443808e-01, -5.09601589e-02, -4.28030906e-02,  1.00019513e+00,
        2.04571149e-01, -8.28658426e-02,  6.98858542e-02,  1.00372587e+00,
       -5.72245147e-01, -2.58774697e-01,  5.62117993e-02,  1.00000108e+00,
       -2.15691183e+00, -7.27729479e-02,  8.45059577e-02,  1.00290832e+00,
        4.93911609e-01, -2.22921736e-01,  2.90256259e-02,  9.99315973e-01,
       -4.64131935e-01,  3.25813793e-02, -8.68602091e-04,  9.98497502e-01,
        1.64133426e+00,  1.47806905e-02,  1.85802804e-02,  9.99981678e-01,
        3.28394070e+00, -4.37437782e-01,  1.91060594e-02,  1.00409469e+00,
        3.81326807e-01, -1.58383726e-01,  4.02655982e-02,  1.00025987e+00,
       -2.84061699e+00, -1.88848728e-01,  5.00840116e-02,  1.00188907e+00,
        7.82083048e-01, -8.28765661e-02, -5.54440302e-03,  1.00067053e+00,
        3.43612215e+00,  

In [114]:
import numpy as np
import pandas as pd
from scipy import optimize
xx=[]
yy=[]
x_N=[]
for a in ['1.dat', '2.dat', '3.dat', '4.dat', '5.dat', '6.dat', '7.dat', '8.dat', '9.dat', '10.dat', '11.dat', '12.dat', '13.dat', '14.dat',]: 
    data1=pd.read_table(a, sep='\s+', names=['a', 'b','c']) 
    x_data=data1['a']
    xx = np.hstack([
        xx,
        x_data
    ]).T
    
    yy = np.hstack([
        yy,
        data1['b']
    ]).T
    x_data=data1['a']
    x_N.append(len(x_data))
Tc=np.array([1.029307615,0.670808905,0.195557495,0.402425385,0.917117575,0.540860525,0.590357705,1.115106295,0.689352065,0.92678156,0.976278745,1.025775925,1.015719525,0.540468115])
def idx(i,j):
    return sum(x_N[:i]) + j
for i in range(14):
    xx[idx(i, 0):idx(i+1, 0)]=xx[idx(i, 0):idx(i+1, 0)]-Tc[i]
def f(xx, *param):
    return np.hstack([
        param[6*i]*xx[idx(i, 0):idx(i+1, 0)]**5 + param[6*i+1]*xx[idx(i, 0):idx(i+1, 0)]**4+param[6*i+2]*xx[idx(i, 0):idx(i+1, 0)]**3+param[6*i+3]*xx[idx(i, 0):idx(i+1, 0)]**2+\
        param[6*i+4]*xx[idx(i, 0):idx(i+1, 0)]+param[6*i+5] for i in range(14)
    ])
def Psi(D,x,y):
    if D==0:
        if x**2-y**2 < 0:
            return np.pi
        else:
            return 0.0
    else:
        return np.real(np.arccos((x**2+D**2-y**2)/(2*D*x)+0j))

def Q(d,r):
    return np.real(np.sqrt((1-(d-r)**2)*((d+r)**2-1)+0j))

def eclips(d,r):
    return np.array([Psi(d_cur,1,r)+Psi(d_cur,r,1)*r**2-Q(d_cur,r)/2 for d_cur in d])

def delta_x(t,t0,tau,l):
    return np.abs(t-t0)/tau*l

def delta(delta_x,impact):
    return np.sqrt(delta_x**2+impact**2)

def fun(t,tau,l,r,impact,L_st,C,t0):
    return L_st+C*(np.pi-eclips(delta(delta_x(t,t0,tau,l),impact),r))

R_st= 1.155 #в радиусаз Солнца +0.014−0.016
R_pl= 1.359 #в радиусах Юпитера +0.016−0.019
au  = 0.04707 #большая полуось в а.е. +0.00045−0.00047
i   = 86.710 #наклон орбиты ±0.050
P   = 3.52474859  #период в днях ±3.8e-07 
MidT= 2826.629283 #среднее время транзита ±8.7e-05
tn  = 218.17120131500087#Время центра затмения
r=R_st/R_pl*695700/71492
impact=au*np.cos(i/180*np.pi)/R_pl/71492*149597870
l=np.sqrt((r+1)**2-impact**2)
tau = P*np.arcsin(l*R_pl*71492/au/149597870)/2/np.pi#длительность транзита
    
def fun2(xx, a1,b1,c1,d1,e1,f1,a2,b2,c2,d2,e2,f2,a3,b3,c3,d3,e3,f3,a4,b4,c4,d4,e4,f4,a5,b5,c5,d5,e5,f5,a6,b6,c6,d6,e6,f6,a7,b7,c7,d7,e7,f7,a8,b8,c8,d8,e8,f8,\
             a9,b9,c9,d9,e9,f9,a10,b10,c10,d10,e10,f10,a11,b11,c11,d11,e11,f11,a12,b12,c12,d12,e12,f12,a13,b13,c13,d13,e13,f13,a14,b14,c14,d14,e14,f14,C,t0):
    return f(xx, a1,b1,c1,d1,e1,f1,a2,b2,c2,d2,e2,f2,a3,b3,c3,d3,e3,f3,a4,b4,c4,d4,e4,f4,a5,b5,c5,d5,e5,f5,a6,b6,c6,d6,e6,f6,a7,b7,c7,d7,e7,f7,a8,b8,c8,d8,e8,f8,\
             a9,b9,c9,d9,e9,f9,a10,b10,c10,d10,e10,f10,a11,b11,c11,d11,e11,f11,a12,b12,c12,d12,e12,f12,a13,b13,c13,d13,e13,f13,a14,b14,c14,d14,e14,f14)+\
C/np.pi*(np.pi-eclips(delta(delta_x(xx,t0,tau,l),impact),r))

zz1=np.zeros((np.size(xx)))
zz1[idx(0, 0):idx(1, 0)]=1
zz2=np.zeros((np.size(xx)))
zz2[idx(1, 0):idx(2, 0)]=1
zz3=np.zeros((np.size(xx)))
zz3[idx(2, 0):idx(3, 0)]=1
zz4=np.zeros((np.size(xx)))
zz4[idx(3, 0):idx(4, 0)]=1
zz5=np.zeros((np.size(xx)))
zz5[idx(4, 0):idx(5, 0)]=1
zz6=np.zeros((np.size(xx)))
zz6[idx(5, 0):idx(6, 0)]=1
zz7=np.zeros((np.size(xx)))
zz7[idx(6, 0):idx(7, 0)]=1
zz8=np.zeros((np.size(xx)))
zz8[idx(7, 0):idx(8, 0)]=1
zz9=np.zeros((np.size(xx)))
zz9[idx(8, 0):idx(9, 0)]=1
zz10=np.zeros((np.size(xx)))
zz10[idx(9, 0):idx(10, 0)]=1
zz11=np.zeros((np.size(xx)))
zz11[idx(10, 0):idx(11, 0)]=1
zz12=np.zeros((np.size(xx)))
zz12[idx(11, 0):idx(12, 0)]=1
zz13=np.zeros((np.size(xx)))
zz13[idx(12, 0):idx(13, 0)]=1
zz14=np.zeros((np.size(xx)))
zz14[idx(13, 0):idx(14, 0)]=1



params, params_covariance = optimize.curve_fit(fun2, xx, yy,p0=[0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,\
                                                                0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0])


In [115]:
params

array([ 2.72451968e+02,  9.34249287e+00, -9.55470850e+00, -3.14397044e-02,
        8.27122957e-02,  9.97699137e-01, -1.18963681e+01, -6.78683811e-01,
        3.52387685e-01,  5.05399113e-02, -3.15823100e-02,  9.98850420e-01,
        2.10176640e+01,  2.88664802e+00, -5.74153047e-01, -1.36928905e-01,
       -3.82678228e-02,  1.00030814e+00, -9.92090197e+01, -1.68222772e+00,
        3.65745257e+00, -8.85723008e-02,  4.61538983e-02,  1.00371725e+00,
       -1.56385110e+02,  9.23747163e+00,  2.53742649e+00, -4.24424422e-01,
        4.42522268e-02,  1.00020102e+00, -2.68238972e+02,  2.04889008e+01,
        4.28743569e+00, -4.40452592e-01,  5.51262364e-02,  1.00354097e+00,
        3.82241801e+01, -9.15499170e+00,  1.68571301e-01, -9.73733238e-02,
        2.80546922e-02,  9.98966405e-01, -7.19549401e+01,  2.79322678e+00,
        1.64591271e+00, -5.69882298e-02, -1.29299030e-02,  9.98630740e-01,
        2.03307695e+02,  1.10704068e+00, -2.93649238e+00,  9.44974788e-03,
        3.87577373e-02,  

In [116]:
np.sqrt(np.diag(params_covariance))

array([2.44091247e+01, 2.54027677e+00, 7.72525114e-01, 5.99364968e-02,
       5.67532429e-03, 2.48482810e-04, 9.60177484e+00, 8.89072846e-01,
       3.17322280e-01, 2.43855678e-02, 2.34672642e-03, 9.75285682e-05,
       9.60348734e+00, 9.03825053e-01, 3.16506182e-01, 2.45622944e-02,
       2.34120049e-03, 9.76500428e-05, 8.25618615e+00, 9.89638272e-01,
       2.75634665e-01, 2.55083306e-02, 2.16967261e-03, 9.80790353e-05,
       3.62039801e+01, 2.56977644e+00, 7.38307720e-01, 4.34231105e-02,
       3.37467511e-03, 1.10347985e-04, 3.63598321e+01, 3.26836980e+00,
       7.06728608e-01, 4.86328131e-02, 3.25267881e-03, 1.12815473e-04,
       1.98619536e+01, 2.41161135e+00, 4.54954771e-01, 4.13146845e-02,
       2.64098896e-03, 1.08657289e-04, 1.54840949e+01, 1.55962761e+00,
       4.16411805e-01, 3.27616152e-02, 2.60462504e-03, 1.03349404e-04,
       3.64822214e+01, 3.88035414e+00, 6.73127257e-01, 5.32197794e-02,
       3.13386028e-03, 1.15070631e-04, 3.63102917e+01, 3.18223364e+00,
      

In [117]:
perr =np.sqrt(np.diag(params_covariance))

In [118]:
np.savetxt('params.dat', params)
np.savetxt('params_covariance.dat', params_covariance)
np.savetxt('perr.dat', perr)

In [137]:
i=14 #вывод конечного результата для полиномов 5 порядка. Обратить внимание, что нумерация i начинается с 0.
vv=[]
t=np.ones((x_N[i],4))
t[:,0]=xx[idx(i, 0):idx(i+1, 0)]
t[:,1]=yy[idx(i, 0):idx(i+1, 0)]
vv=params[6*i]*xx[idx(i, 0):idx(i+1, 0)]**5+params[6*i+1]*xx[idx(i, 0):idx(i+1, 0)]**4+params[6*i+2]*xx[idx(i, 0):idx(i+1, 0)]**3+params[6*i+3]*xx[idx(i, 0):idx(i+1, 0)]**2\
+params[6*i+4]*xx[idx(i, 0):idx(i+1, 0)]+params[6*i+5]
vv=vv+params[84]/np.pi*(np.pi-eclips(delta(delta_x(xx[idx(i, 0):idx(i+1, 0)],params[85],tau,l),impact),r))
t[:,2]=vv
t[:,3]=yy[idx(i, 0):idx(i+1, 0)]-vv
np.savetxt('result15.dat', t)

IndexError: list index out of range